pipeline {
  environment {
    DEPLOY = "${env.BRANCH_NAME == "main" || env.BRANCH_NAME == "develop" ? "true" : "false"}"

  }
  agent {
    kubernetes {
      label 'kubernetes'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:1.11
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  - name: terraform
    image: ghcr.io/mysticrenji/terraform-azurecli:v6
    command: ['cat']
    tty: true
  - name: nodejs
    image: node
    command: ['cat']
    tty: true
  - name: ansible
    image: ghcr.io/mysticrenji/ansible:v12
    imagePullPolicy: Always
    command: ['cat']
    tty: true
  - name: snyk
    image: snyk/snyk-cli:npm
    imagePullPolicy: Always
    command: ['cat']
    tty: true    
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
}
  }

 stages {

      stage('Check for Vulnerabilities') {
     steps {
       container ('snyk') {
        withCredentials([string(credentialsId: 'SNYK_TOKEN', variable: 'SNYK_TOKEN')])
       {
         sh '''
         cd react-app/azure-static
         snyk config set api=$SNYK_TOKEN
         snyk monitor
            '''
       }
       }
     }
      }

   
   stage('Build') {
     steps {
       container ('nodejs') {
         sh '''
         cd react-app/azure-static
         npm install
         npm run build
            '''
         script{
                    zip zipFile: 'static-website.zip', archive: false, dir: 'react-app/azure-static/build'
                    archiveArtifacts artifacts: 'static-website.zip'
              }
       }
     }
   }
     
   stage('Terraform') {
      steps {
      container('terraform') {
        withCredentials([string(credentialsId: 'AZURE_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID'),
                         string(credentialsId: 'AZURE_TENANT_ID', variable: 'ARM_TENANT_ID'),
                         string(credentialsId: 'AZURE_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                         string(credentialsId: 'AZURE_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET')])
                         
        {
        
        sh '''
         cd react-app/terraform
         terraform fmt
         terraform init -input=false
         terraform validate
         terraform plan
         terraform applu -auto-approve
           '''
        // terraform fmt -check -recursive -list=true -diff
        // tflint
        // terraform init -input=false
        // terraform plan -out=tfplan -input=false
        // terraform validate
        // terraform graph | dot -Tpng > terraform-graph.png
        // archiveArtifacts artifacts: 'terraform-graph.png'
       }
      }
   }
 }
    // stage("Publish Approval") {
    //         when { expression { DEPLOY } }
    //         steps {
    //             input message: "Deploy these changes?"
    //         }
    // }


    stage('Ansible Deploy'){
     steps {
       container('ansible') {
       withCredentials([ string(credentialsId: 'AZURE_SUBSCRIPTION_ID', variable: 'AZURE_SUBSCRIPTION_ID'),
                         string(credentialsId: 'AZURE_TENANT_ID', variable: 'AZURE_TENANT'),
                         string(credentialsId: 'AZURE_CLIENT_ID', variable: 'AZURE_CLIENT_ID'),
                         string(credentialsId: 'AZURE_CLIENT_SECRET', variable: 'AZURE_SECRET')])
        {
        checkout scm
        sshagent(['ansiblev1']) {
         sh  '''
         cd react-app/ansible
         ansible --version
         ansible-playbook  azuremblob.yaml -vvv
         '''
       }   
  

       }
       }
     }
   }
   
 }


}
