name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#env:
  # TODO: Change variable to your image's name.
  # IMAGE_NAME: flask-mysql-k3s:v1
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Log into Github Container Registry"        
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: 'Build and push image'
        uses: docker/build-push-action@v6
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
          tags:  v1

