---
- hosts: localhost
  become: false
  collections:
  - azure.azcollection
  tasks:
    - name: Create container foo and upload a file
      azure_rm_storageblob:
        resource_group: terraform-static-apps
        storage_account_name: staticapps30032021
        container: $web
        src: ./nginx.yaml
        content_type: 'multipart/form-data'