---
- hosts: localhost
  become: false
  collections:
  - azure.azcollection
  tasks:
    - name: Create container foo and upload a file
      azure_rm_storageblob:
        resource_group: terraform-static-apps
        storage_account_name: staticapps30032021
        container: '$web'
        batch_upload_dst: '.'
        batch_upload_src: './inventory/'
        state: present
       # blob: 'cloud.jpg'
       # src: './cloud.jpg'
       # content_type: 'multipart/form-data'